/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rgu;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hammed
 */
public class TourAppView extends javax.swing.JFrame {

    /**
     * Creates new form TourAppView
     */
    private boolean withGuide;
    private String tourPackageType = "";
    private ArrayList<Tourist> tourists;
    private ArrayList<TourPackage> tourPackages;
    private ArrayList<Booking> bookings;
    private Tourist tourist;
    private Booking booking;
    private CityTour cityTour;
    private SightseeingTour sightseeingTour;
     private final String POUND = "\u00A3";
    
    public TourAppView() {
        initComponents();
        currency.setText("\u00A3");
        currency2.setText("\u00A3");
        currency3.setText("\u00A3");
        loadInitialData();
        loadAudioLanguage();
    }
    private void loadInitialData(){
        tourPackages = new ArrayList();
        cityTour = new CityTour(true, 500.0, "A city tour in california", "California USA", 2000.0);
        sightseeingTour = new SightseeingTour(200.0, "A sightseeing tour in canada", "Montreal Canada", 1000.0);
        tourPackages.add(cityTour);
        tourPackages.add(sightseeingTour);
        tourist = new Tourist("Mark Joe", "USA", AudioLanguage.ENGLISH);
        tourists = new ArrayList();
        tourists.add(tourist);
        Date bookingDate = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-M-yyy hh:mm:ss");
        String dateTime = dateFormat.format(bookingDate);
        date_time.setText(dateTime); //display current date and time
        Booking firstBooking = new Booking(tourist, sightseeingTour, bookingDate);
        CityTour customCityTour = new CityTour(false, 300.0, "A custom city tour with no guide in India", "Taj Mahal India", 1500.0);
        tourPackages.add(customCityTour);
        Booking secondBooking = new Booking(tourist, customCityTour, new Date());
        bookings = new ArrayList();
        bookings.add(firstBooking);
        bookings.add(secondBooking);
        // Iterate the lists and display content
        for (Tourist tourTourist : tourists){
            touristCombo.addItem(tourTourist.toString());
        }
        for (TourPackage tp : tourPackages){
            packageCombo.addItem(tp.toString());
        }
        // sort bookings according to date andt ime
        Collections.sort(bookings);
        for (Booking book : bookings ){
            bookingsCombo.addItem(book.toString());
        }
    }
    
    private void loadAudioLanguage(){
        for (AudioLanguage value : AudioLanguage.values()){
            languageCombo.addItem(value.toString());
        }
    }
    
    private void showWarning(String message){
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.WARNING_MESSAGE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        touristCombo = new javax.swing.JComboBox<>();
        packageCombo = new javax.swing.JComboBox<>();
        date_time = new javax.swing.JTextField();
        create_booking = new javax.swing.JButton();
        tour_agent = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bookingsCombo = new javax.swing.JComboBox<>();
        cancel_booking = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tourist_name = new javax.swing.JTextField();
        tourist_country = new javax.swing.JTextField();
        languageCombo = new javax.swing.JComboBox<>();
        save_tourist = new javax.swing.JButton();
        new_tourist = new javax.swing.JButton();
        view_bill = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tour_description = new javax.swing.JTextField();
        tour_location = new javax.swing.JTextField();
        tour_cost = new javax.swing.JTextField();
        currency = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cityRadio = new javax.swing.JRadioButton();
        yesRadio = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        noRadio = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        guide_cost = new javax.swing.JTextField();
        currency2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        sightRadio = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        ticketCost = new javax.swing.JTextField();
        currency3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        new_tour_package = new javax.swing.JButton();
        save_tour_package = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tour App");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tourists");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tour Packages");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Date and Time");

        create_booking.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        create_booking.setText("Create Booking");
        create_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_bookingActionPerformed(evt);
            }
        });

        tour_agent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tour_agent.setText("Tour Agent");
        tour_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour_agentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_time, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(packageCombo, 0, 417, Short.MAX_VALUE)
                        .addComponent(touristCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(create_booking)
                    .addComponent(tour_agent, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(touristCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tour_agent)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(date_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(create_booking))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Bookings");

        bookingsCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                bookingsComboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        cancel_booking.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancel_booking.setText("Cancel Booking");
        cancel_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_bookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(bookingsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel_booking)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bookingsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_booking))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tourist", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Country");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Audio Guide Language");

        save_tourist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        save_tourist.setText("Save Tourist");
        save_tourist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_touristActionPerformed(evt);
            }
        });

        new_tourist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        new_tourist.setText("New Tourist");
        new_tourist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_touristActionPerformed(evt);
            }
        });

        view_bill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        view_bill.setText("View Bill");
        view_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_billActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(languageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tourist_country, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(tourist_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(save_tourist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view_bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(new_tourist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(tourist_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(new_tourist)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(tourist_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(view_bill))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(save_tourist))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(languageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tour Package", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Description");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Location");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Tour Cost");

        currency.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        currency.setText("Currency");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        buttonGroup2.add(cityRadio);
        cityRadio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cityRadio.setText("City Tour");
        cityRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(yesRadio);
        yesRadio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        yesRadio.setText("Yes");
        yesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesRadioActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("With Guide");

        buttonGroup1.add(noRadio);
        noRadio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        noRadio.setText("No");
        noRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRadioActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Cost for the guide");

        currency2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        currency2.setText("cur");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel14))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(guide_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currency2)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cityRadio)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yesRadio)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cityRadio)
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(yesRadio)
                    .addComponent(noRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guide_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currency2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        buttonGroup2.add(sightRadio);
        sightRadio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sightRadio.setText("Sightseeing Tour");
        sightRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sightRadioActionPerformed(evt);
            }
        });

        jLabel15.setText("Ticket Cost");

        currency3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        currency3.setText("cur");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ticketCost, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currency3)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(sightRadio))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sightRadio)
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currency3))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        new_tour_package.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        new_tour_package.setText("New Tour Package");
        new_tour_package.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_tour_packageActionPerformed(evt);
            }
        });

        save_tour_package.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        save_tour_package.setText("Save Tour Package");
        save_tour_package.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_tour_packageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(tour_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currency))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tour_location, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tour_description, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(new_tour_package)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(save_tour_package)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tour_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(new_tour_package)
                            .addComponent(save_tour_package))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tour_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tour_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currency)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void create_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_bookingActionPerformed
        // TODO add your handling code here:
        try{
            String dateTime = date_time.getText();
            if (dateTime.equals("")) this.showWarning("date and time is required");
            int touristIndex = touristCombo.getSelectedIndex();
            int packageIndex = packageCombo.getSelectedIndex();
            Date bookDate = new SimpleDateFormat("dd-M-yyyy hh:mm:ss").parse(dateTime);
            // get the object of tourist and tourpackage from their list and create the booking
            Booking newBooking = new Booking(tourists.get(touristIndex), tourPackages.get(packageIndex), bookDate);
            bookings.add(newBooking);
            bookingsCombo.addItem(newBooking.toString());
            JOptionPane.showMessageDialog(this, "Booking created");
        }catch(IllegalArgumentException iae){
            this.showWarning(iae.toString());
        } catch (ParseException ex) {
            Logger.getLogger(TourAppView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_create_bookingActionPerformed

    private void bookingsComboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_bookingsComboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        // get the index of the booking.
        int bookingIndex = bookingsCombo.getSelectedIndex();
        Booking selectedBooking = bookings.get(bookingIndex);
        //get the tourist
        Tourist selectedTourist = selectedBooking.getTourist();
        // display touristt properties
        tourist_name.setText(selectedTourist.getName());
        tourist_country.setText(selectedTourist.getCountry());
        languageCombo.setSelectedItem(selectedTourist.getAudioLanguage());
        // get the tourPackage
        TourPackage selectedTourPackage = selectedBooking.getTourPackage();
        // display tour package properties
        tour_description.setText(selectedTourPackage.getDescription());
        tour_location.setText(selectedTourPackage.getLocation());
        tour_cost.setText(String.valueOf(selectedTourPackage.getCost()));
        // Check for type of selected tour package and display accordingly
        if(selectedTourPackage instanceof CityTour){
            cityRadio.setSelected(true);
            CityTour selectedCityTour = (CityTour) selectedTourPackage;
            if(selectedCityTour.isWithGuide()) {
                   yesRadio.setSelected(true);
                   guide_cost.setText(String.valueOf(selectedCityTour.getGuideCost()));
            }else{
                noRadio.setSelected(true);
            }
            sightRadio.setSelected(false);
            ticketCost.setText("");
            
        }else{
            SightseeingTour selectedSiteTour = (SightseeingTour) selectedTourPackage;
            sightRadio.setSelected(true);
            ticketCost.setText(String.valueOf(selectedSiteTour.getTicketCost()));
            cityRadio.setSelected(false);
            yesRadio.setSelected(false);
            noRadio.setSelected(false);
            guide_cost.setText("");
            
        }
    }//GEN-LAST:event_bookingsComboPopupMenuWillBecomeInvisible

    private void new_touristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_touristActionPerformed
        // TODO add your handling code here:
        tourist_name.setText("");
        tourist_country.setText("");
    }//GEN-LAST:event_new_touristActionPerformed

    private void new_tour_packageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_tour_packageActionPerformed
        // TODO add your handling code here:
        tour_description.setText("");
        tour_location.setText("");
        tour_cost.setText("");
        cityRadio.setSelected(false);
        yesRadio.setSelected(false);
        noRadio.setSelected(false);
        guide_cost.setText("");
        sightRadio.setSelected(false);
        ticketCost.setText("");
    }//GEN-LAST:event_new_tour_packageActionPerformed

    private void view_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_billActionPerformed
        // TODO add your handling code here:
        // get the index of the booking.
        int bookingIndex = bookingsCombo.getSelectedIndex();
        Booking selectedBooking = bookings.get(bookingIndex);
        //get the tourist
        Tourist selectedTourist = selectedBooking.getTourist();
        BookingUtil bookingUtil = new BookingUtil();
        double[] bill = bookingUtil.calculateBill(bookings, selectedTourist);
        String billInfo = selectedTourist.getName() + "'s total bill is "+ bill[0] + POUND + " and after discount it is " + bill[1] + POUND;
        JOptionPane.showMessageDialog(this, billInfo);
    }//GEN-LAST:event_view_billActionPerformed

    private void save_touristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_touristActionPerformed
        // TODO add your handling code here:
        String name = tourist_name.getText();
        String country =  tourist_country.getText();
        if (name.equals("")) this.showWarning("Tourist Name is required");
        else if (country.equals("")) this.showWarning("Tourist Country is required");
        AudioLanguage language = AudioLanguage.valueOf(languageCombo.getSelectedItem().toString());
        Tourist newTourist = new Tourist(name, country, language );
        tourists.add(newTourist);
        touristCombo.addItem(newTourist.toString());
        JOptionPane.showMessageDialog(this, "Tourist saved");
    }//GEN-LAST:event_save_touristActionPerformed

    private void cancel_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_bookingActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Are sure to cancel this booking", "Confirm Action", JOptionPane.YES_NO_OPTION);
        if(response == 0){
            int bookingIndex = bookingsCombo.getSelectedIndex();
            bookings.remove(bookingIndex);
            bookingsCombo.removeItemAt(bookingIndex);
            JOptionPane.showMessageDialog(this, "Booking canceled");
        }  
    }//GEN-LAST:event_cancel_bookingActionPerformed

    private void yesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesRadioActionPerformed
        // TODO add your handling code here:
        withGuide = true;
    }//GEN-LAST:event_yesRadioActionPerformed

    private void noRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRadioActionPerformed
        // TODO add your handling code here:
        withGuide = false;
        guide_cost.setText("");
    }//GEN-LAST:event_noRadioActionPerformed

    private void cityRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityRadioActionPerformed
        // TODO add your handling code here:
        tourPackageType = "cityTour";
    }//GEN-LAST:event_cityRadioActionPerformed

    private void sightRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sightRadioActionPerformed
        // TODO add your handling code here:
        tourPackageType = "sightSeeing";
    }//GEN-LAST:event_sightRadioActionPerformed

    private void save_tour_packageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_tour_packageActionPerformed
        // TODO add your handling code here:
        String description = tour_description.getText();
        String location = tour_location.getText();
        double guideCost = 0.0;
        double ticket = 0.0;
        if (description.isEmpty()) {
            this.showWarning("Description is required");
            return;
        }
        if (location.isEmpty()) {
            this.showWarning("Location is required");
            return;
        }
        if (tour_cost.getText().isEmpty()) {
            this.showWarning("Tour cost is required");
            return;
        }
        double tourCost = Double.parseDouble(tour_cost.getText());
        if(tourPackageType.isEmpty()) {
            this.showWarning("Please choose a package type: either city tour or sightseein tour");
            return;
        }
        if (tourPackageType.equals("cityTour")) {
            if (guide_cost.getText().isEmpty()){
                this.showWarning("Guide cost is required");
                return;
            }
            if (withGuide) {
                guideCost = Double.parseDouble(guide_cost.getText());
            }
            cityTour = new CityTour(withGuide, guideCost, description, location, tourCost);
            tourPackages.add(cityTour);
            packageCombo.addItem(cityTour.toString());
        }else if (tourPackageType.equals("sightSeeing")) {
            if (ticketCost.getText().isEmpty()){
                this.showWarning("Ticket cost is required");
                return;
            }
            ticket = Double.parseDouble(ticketCost.getText());
            sightseeingTour = new SightseeingTour(ticket, description, location, tourCost);
            tourPackages.add(sightseeingTour);
            packageCombo.addItem(sightseeingTour.toString());
        }
        JOptionPane.showMessageDialog(this, "Package created");
    }//GEN-LAST:event_save_tour_packageActionPerformed

    private void tour_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour_agentActionPerformed
        // TODO add your handling code here:
        TourAppAgentView tourAgent = new TourAppAgentView();
        tourAgent.setLocationRelativeTo(null);
        tourAgent.setVisible(true);
    }//GEN-LAST:event_tour_agentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TourAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TourAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TourAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TourAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TourAppView tourAppView = new TourAppView();
                tourAppView.setLocationRelativeTo(null);
                tourAppView.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bookingsCombo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancel_booking;
    private javax.swing.JRadioButton cityRadio;
    private javax.swing.JButton create_booking;
    private javax.swing.JLabel currency;
    private javax.swing.JLabel currency2;
    private javax.swing.JLabel currency3;
    private javax.swing.JTextField date_time;
    private javax.swing.JTextField guide_cost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> languageCombo;
    private javax.swing.JButton new_tour_package;
    private javax.swing.JButton new_tourist;
    private javax.swing.JRadioButton noRadio;
    private javax.swing.JComboBox<String> packageCombo;
    private javax.swing.JButton save_tour_package;
    private javax.swing.JButton save_tourist;
    private javax.swing.JRadioButton sightRadio;
    private javax.swing.JTextField ticketCost;
    private javax.swing.JButton tour_agent;
    private javax.swing.JTextField tour_cost;
    private javax.swing.JTextField tour_description;
    private javax.swing.JTextField tour_location;
    private javax.swing.JComboBox<String> touristCombo;
    private javax.swing.JTextField tourist_country;
    private javax.swing.JTextField tourist_name;
    private javax.swing.JButton view_bill;
    private javax.swing.JRadioButton yesRadio;
    // End of variables declaration//GEN-END:variables
}
